// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATsyiQ0weei4MjA-TkhWRQq4X1RP0D_Og',
    appId: '1:558387718828:web:ffc18d9d9d59f31514cd09',
    messagingSenderId: '558387718828',
    projectId: 'dalelapp-89b01',
    authDomain: 'dalelapp-89b01.firebaseapp.com',
    storageBucket: 'dalelapp-89b01.appspot.com',
    measurementId: 'G-DESJ0R6BHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ2bHj50uZMTL7YwGAAArLZEVMbNhTc_k',
    appId: '1:558387718828:android:e3da9efc4c98785c14cd09',
    messagingSenderId: '558387718828',
    projectId: 'dalelapp-89b01',
    storageBucket: 'dalelapp-89b01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6aaAO7Pk1TGDifS1peoAGbrp9K-26BH4',
    appId: '1:558387718828:ios:78a53113d06d8c8514cd09',
    messagingSenderId: '558387718828',
    projectId: 'dalelapp-89b01',
    storageBucket: 'dalelapp-89b01.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6aaAO7Pk1TGDifS1peoAGbrp9K-26BH4',
    appId: '1:558387718828:ios:f8f48841308df3ef14cd09',
    messagingSenderId: '558387718828',
    projectId: 'dalelapp-89b01',
    storageBucket: 'dalelapp-89b01.appspot.com',
    iosBundleId: 'com.example.dalelApp.RunnerTests',
  );
}
